# Configuration file for the WWCS application

servicepass: "wwcs1234" # Password for service applications
wwcs_domain: "wwcs.tj" # Domain name of the server

# Define area of WWCS application

minlat: 36.5 
maxlat: 41.5  
minlon: 67   
maxlon: 75.5

# Define view point of leaflet map

setlat: 38.5
setlon: 71

# Define default station name

dashboard_default_station: "CLIMDYU001"

# Define GADM country code (https://gadm.org/)

gadm0: "TJK"

# Define time-zone (https://en.wikipedia.org/wiki/List_of_tz_database_time_zones)

timezone_country: "Asia/Dushanbe"

# Parameters for EMOS

train_period: 30 # Days with which to train temperature forecasts
forecast_days: 10 # Days to consider of ECMWF forecasts
miss_val: 0.50 # Amount of missing values to allow in the station data
emos_formula: "Temperature_mean ~ IFS_T_mea + IFS_T_DTR  | IFS_T_std"

# Parameters for global EMOS

resolution_gEMOS: 0.005
gemos_formula: "Observations ~ IFS_T_mea + division(ELEV,100) + division(HSURF,100) + TPI5 + division(TPI100,100) | IFS_T_std + division(ELEV,100)"

# Warning parameters

spatial_threshold: 0.5 # 0.5 = 50 % of grid points within an area that exceed the threshold
warning_days: 5 # Window to calculate the warning
warning_default_station: "CLIMNUR002"

# Irrigation parameters

irrigation_default_station: "LAKH012-3" # Default station for irrigation

# Planting parameters

planting_default_station: "CLIMNUR002"
soil_fcst_days: 7 # Days to consider of forecasts for soil temperature
proxy_formula: "Temperature ~ T2_lag3 +  T2_lag2 + TemperatureAir + RH"
lag3: 15 # Days to consider for lag 3
lag2: 10 # Days to consider for lag 2
lag1: 3 # Days to consider for lag 1

# Harvest parameters

harvest_default_station: "CLIMNUR002"
past_rain_thrs: 1 # Threshold for past rain in mm
future_rain_thrs: 1 # Threshold for future rain in mm
past_rain_days: 5 # Threshold for past rain in mm
future_rain_days: 5 # Threshold for future rain in mm
