name: ruff (Python linter)

on:
  pull_request:
  push:

permissions:
  contents: read

jobs:
  ruff:
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - run: pip install ruff

    - run: ruff check
